apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: wisecowim
        ports:
        - containerPort: 4499
        volumeMounts:
        - name: tls-volume
          mountPath: /etc/tls
      volumes:
      - name: tls-volume
        secret:
          secretName: wisecow-tls


# let the image name be wisecowim