name: Docker Image Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: <dockerusername>
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t wisecowim .
          docker push <dockerusername>/wisecowim

      - name: Deploy to Kubernetes
        uses: kubernetes/deploy-action@v2
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          deployment: wisecow-deployment
          image: <dockerusername>/wisecowim
