apiVersion: v1
kind: Service
metadata:
  name: wisecow
spec:
  selector:
    app: wisecow
  ports:
  - name: https
    port: 4499
    targetPort: 4499
  type: LoadBalancer
  tls:
    secretName: wisecow-tls