# script is used to start a TLS-enabled server that listens on port 4499 and responds with a message generated by the cowsay and fortune commands.

bash
#!/usr/bin/env bash
SRVPORT=4499
RSPFILE=response
TLS_CERT=/etc/tls/tls.crt
TLS_KEY=/etc/tls/tls.key

while true; do
  echo "Waiting for connection on port $SRVPORT..."
  nc -l -p $SRVPORT -c "openssl s_client -cert $TLS_CERT -key $TLS_KEY -connect localhost:$SRVPORT" > $RSPFILE
  echo "Connection established, generating response..."
  FORTUNE=$(fortune)
  COWSAY=$(cowsay -f $(ls /usr/share/cowsay/cows/ | shuf -n 1) "$FORTUNE")
  echo "$COWSAY" > $RSPFILE
done
